Upgrade base docker image to java 21
Seems like 0.53.x requires newer java, currently container crashes with:

> java.lang.NoClassDefFoundError: java/util/SequencedCollection

Ref:

https://discourse.metabase.com/t/upgrade-isnt-upgrading/204957